import type { Client, Invoice } from '@prisma/client';
import { prisma } from '../config/prisma.js';
import { recordActivity } from './activity.service.js';

const money = (value: unknown) => Number(value ?? 0);

function monthRange(year: number, month: number) {
  return {
    start: new Date(Date.UTC(year, month - 1, 1)),
    end: new Date(Date.UTC(year, month, 1))
  };
}

function addDays(date: Date, days: number) {
  const next = new Date(date);
  next.setUTCDate(next.getUTCDate() + days);
  return next;
}

function invoiceNumber(client: Client, periodStart: Date) {
  const y = periodStart.getUTCFullYear();
  const m = String(periodStart.getUTCMonth() + 1).padStart(2, '0');
  return `SC-${y}${m}-${client.id.slice(-6).toUpperCase()}`;
}

function descriptionFor(client: Client, periodStart: Date, periodEnd: Date) {
  const service = client.service.replaceAll('_', ' ').toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase());
  const month = periodStart.toLocaleString('en', { month: 'long', year: 'numeric', timeZone: 'UTC' });
  return `${service} - ${month}`;
}

async function createInvoiceForClient(client: Client, periodStart: Date, periodEnd: Date) {
  const existing = await prisma.invoice.findFirst({
    where: { clientId: client.id, autoGenerated: true, billingPeriodStart: periodStart, billingPeriodEnd: periodEnd }
  });
  if (existing) return { invoice: existing, created: false };

  const invoice = await prisma.invoice.create({
    data: {
      clientId: client.id,
      invoiceNumber: invoiceNumber(client, periodStart),
      amount: money(client.monthlyFee),
      currency: client.currency,
      issueDate: periodStart,
      dueDate: addDays(periodStart, 14),
      billingPeriodStart: periodStart,
      billingPeriodEnd: periodEnd,
      autoGenerated: true,
      status: 'SENT',
      description: descriptionFor(client, periodStart, periodEnd)
    },
    include: { client: true, payments: true }
  });
  await recordActivity({ action: 'CREATED', entityType: 'INVOICE', entityId: invoice.id, title: `Auto invoice ${invoice.invoiceNumber} created`, details: client.name });
  return { invoice, created: true };
}

function shouldGenerateForPeriod(client: Client, periodStart: Date, periodEnd: Date) {
  if (client.status !== 'ACTIVE') return false;
  if (client.contractStartDate >= periodEnd) return false;
  if (client.billingFrequency === 'MONTHLY') return true;
  if (client.billingFrequency === 'YEARLY') return client.contractStartDate.getUTCMonth() === periodStart.getUTCMonth();
  return false;
}

export async function generateInvoicesForPeriod(year: number, month: number) {
  const { start, end } = monthRange(year, month);
  const clients = await prisma.client.findMany({ where: { status: 'ACTIVE' } });
  const results: Array<{ invoice: Invoice; created: boolean }> = [];

  for (const client of clients) {
    if (client.billingFrequency === 'ONE_TIME') {
      const existing = await prisma.invoice.findFirst({ where: { clientId: client.id, autoGenerated: true } });
      if (existing) {
        results.push({ invoice: existing, created: false });
        continue;
      }
      const oneTimeStart = client.contractStartDate;
      const oneTimeEnd = new Date(Date.UTC(oneTimeStart.getUTCFullYear(), oneTimeStart.getUTCMonth() + 1, 1));
      results.push(await createInvoiceForClient(client, oneTimeStart, oneTimeEnd));
      continue;
    }

    if (shouldGenerateForPeriod(client, start, end)) {
      results.push(await createInvoiceForClient(client, start, end));
    }
  }

  return {
    period: { year, month, start, end },
    created: results.filter((item) => item.created).map((item) => item.invoice),
    skipped: results.filter((item) => !item.created).map((item) => item.invoice)
  };
}

export async function generateCurrentPeriodInvoices() {
  const now = new Date();
  return generateInvoicesForPeriod(now.getUTCFullYear(), now.getUTCMonth() + 1);
}
