export type ClientService = 'META_ADS' | 'TIKTOK_ADS' | 'GOOGLE_ADS' | 'SOCIAL_MEDIA_MANAGEMENT' | 'CONTENT_CREATION' | 'SHOPIFY_STORE' | 'WEBSITE_DEVELOPMENT' | 'WEB_APPLICATION' | 'MOBILE_APPLICATION' | 'BRANDING' | 'OTHER';
export type ClientStatus = 'ACTIVE' | 'PAUSED' | 'COMPLETED';
export type PaymentMethod = 'CASH' | 'BANK' | 'WHISH' | 'OMT' | 'TRANSFER' | 'OTHER';
export type PaymentFrequency = 'ONE_TIME' | 'MONTHLY' | 'YEARLY';
export type ExpenseCategory = 'OFFICE' | 'SOFTWARE' | 'ADS' | 'FREELANCER' | 'EMPLOYEE' | 'INTERNET' | 'PHONE' | 'TRANSPORTATION' | 'EQUIPMENT' | 'UTILITIES' | 'MARKETING' | 'OTHER';

export interface Client {
  id: string;
  name: string;
  company?: string;
  phone?: string;
  email?: string;
  services: ClientService[];
  monthlyFee: number;
  billingFrequency: PaymentFrequency;
  currency: string;
  status: ClientStatus;
  contractStartDate: string;
  invoiceDescription?: string;
  notes?: string;
  createdAt: string;
}

export interface Income {
  id: string;
  clientId: string;
  client?: Client;
  invoiceId?: string;
  amount: number;
  currency: string;
  date: string;
  paymentMethod: PaymentMethod;
  frequency: PaymentFrequency;
  referenceNumber?: string;
  description?: string;
  invoiceNumber?: string;
}

export type InvoiceStatus = 'DRAFT' | 'SENT' | 'PARTIAL' | 'PAID' | 'OVERDUE' | 'CANCELLED';

export interface InvoicePayment {
  id: string;
  invoiceId: string;
  amount: number;
  currency: string;
  date: string;
  paymentMethod: PaymentMethod;
  referenceNumber?: string;
  notes?: string;
}

export interface Invoice {
  id: string;
  clientId: string;
  client?: Client;
  invoiceNumber: string;
  amount: number;
  paidAmount: number;
  outstanding?: number;
  currency: string;
  issueDate: string;
  dueDate: string;
  billingPeriodStart?: string;
  billingPeriodEnd?: string;
  autoGenerated: boolean;
  status: InvoiceStatus;
  computedStatus?: InvoiceStatus;
  description?: string;
  notes?: string;
  payments: InvoicePayment[];
}

export type AttachmentEntityType = 'CLIENT' | 'INCOME' | 'EXPENSE' | 'INVOICE' | 'ADVANCE';

export interface Attachment {
  id: string;
  entityType: AttachmentEntityType;
  entityId: string;
  title: string;
  url: string;
  notes?: string;
  createdAt: string;
}

export interface ActivityLog {
  id: string;
  action: 'CREATED' | 'UPDATED' | 'DELETED' | 'PAID' | 'ATTACHED';
  entityType: string;
  entityId?: string;
  title: string;
  details?: string;
  createdAt: string;
}

export interface Expense {
  id: string;
  title: string;
  amount: number;
  currency: string;
  category: ExpenseCategory;
  paymentMethod: PaymentMethod;
  frequency: PaymentFrequency;
  date: string;
  vendor?: string;
  receiptNumber?: string;
  notes?: string;
}

export interface AdvanceRepayment {
  id: string;
  advanceId: string;
  amount: number;
  currency: string;
  date: string;
  paymentMethod: PaymentMethod;
  notes?: string;
}

export interface OwnerAdvance {
  id: string;
  title: string;
  amount: number;
  currency: string;
  date: string;
  source?: string;
  plannedInstallments?: number;
  installmentAmount?: number;
  nextDueDate?: string;
  notes?: string;
  status: 'OPEN' | 'PAID';
  computedStatus?: 'OPEN' | 'PAID';
  repaid: number;
  outstanding: number;
  repayments: AdvanceRepayment[];
}

export interface Paginated<T> {
  items: T[];
  pagination: { page: number; limit: number; total: number; pages: number };
}
