ALTER TABLE "invoices" ADD COLUMN "billingPeriodStart" TIMESTAMP(3);
ALTER TABLE "invoices" ADD COLUMN "billingPeriodEnd" TIMESTAMP(3);
ALTER TABLE "invoices" ADD COLUMN "autoGenerated" BOOLEAN NOT NULL DEFAULT false;

CREATE INDEX "invoices_clientId_billingPeriodStart_billingPeriodEnd_idx" ON "invoices"("clientId", "billingPeriodStart", "billingPeriodEnd");
