WITH ranked_one_time_invoices AS (
  SELECT
    invoice."id",
    invoice."billingPeriodStart",
    client."contractStartDate",
    ROW_NUMBER() OVER (
      PARTITION BY invoice."clientId"
      ORDER BY
        CASE
          WHEN invoice."billingPeriodStart" >= date_trunc('month', client."contractStartDate")
            AND invoice."billingPeriodStart" < date_trunc('month', client."contractStartDate") + INTERVAL '1 month'
          THEN 0
          ELSE 1
        END,
        invoice."createdAt"
    ) AS invoice_number
  FROM "invoices" AS invoice
  INNER JOIN "clients" AS client ON client."id" = invoice."clientId"
  WHERE client."billingFrequency" = 'ONE_TIME'
    AND invoice."autoGenerated" = TRUE
)
DELETE FROM "invoices" AS invoice
USING ranked_one_time_invoices AS ranked
WHERE invoice."id" = ranked."id"
  AND (
    ranked."billingPeriodStart" IS NULL
    OR ranked."billingPeriodStart" < date_trunc('month', ranked."contractStartDate")
    OR ranked."billingPeriodStart" >= date_trunc('month', ranked."contractStartDate") + INTERVAL '1 month'
    OR ranked.invoice_number > 1
  );
